### ISSUE TITLE
support for mysql and postgresql

### ISSUE THREAD

**Issue by NetoDevel** [NetoDevel/spring-boot-scaffold-kotlin#6]
in project creation specify which database

example:

`cli -spring g new myproject mysql` 
`cli -spring g new myproject postgres` 

Files to change the type of database

**application.properties**

_for mysql_
`spring.datasource.url = jdbc: mysql: // localhost / paydomestic`

_for postgresql_
`spring.datasource.url = jdbc: postgresql: // localhost: 5432 / blood`

**dependency in pom.xml**

_for mysql_
```
<Dependency>
       <GroupId> mysql </ groupId>
       <ArtifactId> mysql-connector-java </ artifactId>
</ Dependency>
```

_for postgres_
```
<Dependency>
       <GroupId> postgresql </ groupId> 
       <ArtifactId> postgresql </ artifactId>
       <Version> 9.1-901-1.jdbc4 </ version> 
</Dependency>
```

**Comment by NetoDevel** [comment]
@ivanmarreta

**Comment by ivanmarreta** [comment]
@NetoDevel What the default database?

**Comment by ivanmarreta** [comment]
I got mysql as default db.
